import Link from 'next/link'
import PageHero from '@/components/sections/PageHero'

export const metadata = {
  title: 'Terms of Service | KuzaConnect',
  description: 'Terms and conditions for using KuzaConnect\'s website, AI tools, and services.',
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-h3 mb-3" style={{ color: 'var(--kuza-purple-dark)' }}>{title}</h2>
      <div className="space-y-3 text-body" style={{ color: '#4b5563', lineHeight: 1.75 }}>
        {children}
      </div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <>
      <PageHero
        tag="Legal"
        heading="Terms of Service"
        description="The terms and conditions that govern your use of KuzaConnect's website, AI tools, and services."
      />

      <div className="section-pad" style={{ background: 'white' }}>
        <div className="container-xl" style={{ maxWidth: '760px' }}>

          <p className="text-caption mb-10" style={{ color: '#9ca3af' }}>
            Last updated: January 2025
          </p>

          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using the KuzaConnect website (kuzaconnect.com) or any of our AI tools,
              you agree to be bound by these Terms of Service. If you do not agree to these terms,
              please do not use our website or tools.
            </p>
            <p>
              These Terms apply to all visitors, users, and others who access or use KuzaConnect&apos;s
              digital services, including the Impact Matcher, Capacity Assessment, M&amp;E Analyzer,
              and Kuza Assistant chatbot.
            </p>
          </Section>

          <Section title="2. Our Services">
            <p>KuzaConnect provides:</p>
            <ul className="space-y-2 pl-5 list-disc">
              <li>
                <strong style={{ color: '#1a1630' }}>Free AI tools</strong> — the Impact Matcher, Capacity
                Assessment, and M&amp;E Analyzer are available at no cost and without registration.
                These tools are provided as-is for informational and planning purposes.
              </li>
              <li>
                <strong style={{ color: '#1a1630' }}>AI chatbot</strong> — the Kuza Assistant provides
                general information about KuzaConnect&apos;s services and approach. Responses are
                AI-generated and should not be relied upon as formal professional advice.
              </li>
              <li>
                <strong style={{ color: '#1a1630' }}>Consulting services</strong> — paid engagements
                are governed by separate contracts between KuzaConnect and the client organisation.
              </li>
            </ul>
          </Section>

          <Section title="3. Use of AI Tools">
            <p>
              Our AI tools are designed to provide guidance and recommendations based on the inputs
              you provide. By using these tools, you acknowledge that:
            </p>
            <ul className="space-y-2 pl-5 list-disc">
              <li>
                Outputs are generated by artificial intelligence and are for informational purposes only.
                They do not constitute professional consulting advice.
              </li>
              <li>
                Results should be reviewed critically and validated against your organisation&apos;s
                specific context before being acted upon.
              </li>
              <li>
                For the M&amp;E Analyzer, you are responsible for ensuring you have the right to upload
                and process any documents you submit. Do not upload documents containing sensitive
                personal data or confidential information belonging to third parties without authorisation.
              </li>
              <li>
                KuzaConnect does not retain the content of your tool sessions after they end.
              </li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to use our website or tools to:</p>
            <ul className="space-y-2 pl-5 list-disc">
              <li>Violate any applicable laws or regulations</li>
              <li>Upload malicious files, viruses, or harmful code</li>
              <li>Attempt to gain unauthorised access to our systems</li>
              <li>Scrape, harvest, or extract data from our website in bulk without permission</li>
              <li>Use our tools to generate content for purposes that are misleading, harmful, or fraudulent</li>
              <li>Impersonate KuzaConnect or misrepresent your affiliation with us</li>
            </ul>
          </Section>

          <Section title="5. Intellectual Property">
            <p>
              All content on the KuzaConnect website, including text, graphics, logos, and tool designs,
              is the property of KuzaConnect and is protected by applicable intellectual property laws.
            </p>
            <p>
              You may not reproduce, distribute, or create derivative works from our content without
              our prior written permission. Brief quotations for non-commercial purposes with proper
              attribution are permitted.
            </p>
            <p>
              The outputs generated by our AI tools based on your inputs may be used by you for your
              own organisational purposes. KuzaConnect retains no claim over your use of AI-generated
              recommendations.
            </p>
          </Section>

          <Section title="6. Disclaimers and Limitation of Liability">
            <p>
              Our website and AI tools are provided &ldquo;as is&rdquo; without warranties of any kind, express or
              implied. KuzaConnect does not warrant that:
            </p>
            <ul className="space-y-2 pl-5 list-disc">
              <li>The tools will be uninterrupted, error-free, or free of bugs</li>
              <li>AI-generated outputs will be accurate, complete, or suitable for your specific needs</li>
              <li>The website will be available at all times</li>
            </ul>
            <p>
              To the fullest extent permitted by law, KuzaConnect shall not be liable for any indirect,
              incidental, special, or consequential damages arising from your use of our website or
              tools, including but not limited to loss of data, loss of revenue, or loss of business
              opportunities.
            </p>
          </Section>

          <Section title="7. Third-Party Services">
            <p>
              Our AI tools are powered by Anthropic&apos;s Claude API and our data infrastructure uses
              Supabase and Vercel. Your use of our tools is also subject to their respective terms of
              service. KuzaConnect is not responsible for the availability or performance of third-party
              services.
            </p>
          </Section>

          <Section title="8. Links to External Sites">
            <p>
              Our website may contain links to external websites. These links are provided for
              convenience only. KuzaConnect does not endorse or take responsibility for the content
              or practices of any external sites.
            </p>
          </Section>

          <Section title="9. Changes to These Terms">
            <p>
              KuzaConnect reserves the right to update these Terms of Service at any time. The
              &ldquo;Last updated&rdquo; date at the top of this page will reflect changes. Continued use of our
              website or tools after changes are posted constitutes acceptance of the updated terms.
            </p>
          </Section>

          <Section title="10. Governing Law">
            <p>
              These Terms of Service are governed by and construed in accordance with the laws of
              Kenya. Any disputes arising from these terms shall be subject to the jurisdiction of
              the courts of Nairobi, Kenya.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              If you have questions about these Terms of Service, please contact us:
            </p>
            <div
              className="mt-4 p-5 rounded-xl"
              style={{ background: 'var(--kuza-cream)', border: '1px solid #e4e0d8' }}
            >
              <p className="font-semibold mb-1" style={{ color: 'var(--kuza-purple-dark)' }}>KuzaConnect</p>
              <p>Email: <a href="mailto:info@kuzaconnect.com" style={{ color: 'var(--kuza-purple)' }}>info@kuzaconnect.com</a></p>
              <p>Phone: +254 729 980718</p>
              <p>Location: Nairobi, Kenya</p>
            </div>
          </Section>

          <div className="pt-8 border-t" style={{ borderColor: '#e4e0d8' }}>
            <Link href="/privacy" style={{ color: 'var(--kuza-purple)' }} className="text-sm hover:underline">
              View our Privacy Policy
            </Link>
          </div>

        </div>
      </div>
    </>
  )
}
